### ISSUE TITLE
Remember previous position in timeline when reopening app 

### ISSUE THREAD

**Issue by caoilte** [pachli/pachli-android#53] opened 2023-09-16 22:24 UTC
I suspect there are a couple of ways to trigger this bug. Here's how i just did it.

- I was looking at a thread on someone's timeline
- I closed the app
- I reopened the app a few hours later and I was still on their thread (yay! rehydrate remembered where i was)
- I navigated back to the homepage
- Pachli jumped me ahead to the latest toot instead of restoring me to where I was before I clicked into someones thread.
- I had to scroll back six hours and figure out where i left off reading the timeline.

This is an inherited Tusky issue (hilariously official mastodon client also has it) that the auto-timeline loading in pachlii has sadly made worse. In Tusky it wouldn't have automatically have loaded the missing toots, so it wouldn't have automatically jumped me ahead of them all (although it would have jumped me to the head of whichever toots i'd had loaded so it would have been effectively as bad).

The fix is to remember the point up to which you've read your timeline and restore to that point when returning to the homepage from some other part of the app.

**Comment by nikclayton** [comment] 2023-09-17 12:20
Thanks for the report. This is mostly fixed with

- https://github.com/pachli/pachli-android/pull/44
- https://github.com/pachli/pachli-android/pull/49

which will be in the 1.1 release. They appear to work correctly in almost all scenarios that involve returning to the app that I've tested (warm start, cold start after installing a new version of the app, cold start after opening the "Recents" list and swiping the app away).

There's one issue that they don't seem to resolve -- leaving the phone overnight, then unlocking the phone and opening the app. The logs show that the reading position is being restored, but the reading position jumps to the top. I'm testing another fix for that now, but since I can't trigger the problem on demand it's difficult to know for sure that it's resolved the issue.

**Comment by caoilte** [comment] 2023-09-17 13:27
Nice!
Haven't looked at the code, but would it help if the code was refactored to make it impossible to load the home screen from the top (ie the only way to load it was via read position).

Feel free to close if this is a dupe. Looking forward to 1.1. already happily switched from tusky.

**Comment by nikclayton** [comment] 2023-09-17 18:51
That's pretty much what it should be doing at the moment. The only time there isn't a saved read position is if you're running the app for the very first time.

If I consider the following two scenarios (with the code on `develop` right now):

1. Open the app, scroll to a position on the home timeline, leave the app by going back to the launcher, do a bunch of other things on the device so Android closes Pachli, and
2. Open the app, scroll to a position on the home timeline, open the "recents" list of apps, and swipe Pachli away so it's forceably closed

and then re-open Pachli, the behaviour should be identical -- you should be returned to the home timeline, and the reading position should be restored to the first status that was completely visible at the top of the screen when you left the app.

That works for scenario 2, consistently.  It does not work for scenario 1, and I don't currently understand why. The logs in both cases are identical, showing:

- The ID of the status is correctly saved and retrieved
- The network requests to the Mastodon server are correct (i.e., they contain the correct status IDs)
- Data is fetched and added to the list in the same order
- Debug logs show the reading position being restored (by scrolling the list) appear, and the ID of the status to scroll to is correct

I can't reproduce scenario 1 in an emulator either.

This is something the Android libraries are supposed to handle automatically, https://developer.android.com/reference/kotlin/androidx/paging/PagingDataAdapter notes:

> State Restoration: To be able to restore [RecyclerView](https://developer.android.com/reference/kotlin/androidx/recyclerview/widget/RecyclerView) state (e.g. scroll position) after a configuration change / application recreate, [PagingDataAdapter](https://developer.android.com/reference/kotlin/androidx/paging/PagingDataAdapter) calls [RecyclerView.Adapter.setStateRestorationPolicy](https://developer.android.com/reference/kotlin/androidx/recyclerview/widget/RecyclerView.Adapter#setStateRestorationPolicy(androidx.recyclerview.widget.RecyclerView.Adapter.StateRestorationPolicy)) with [RecyclerView.Adapter.StateRestorationPolicy.PREVENT](https://developer.android.com/reference/kotlin/androidx/recyclerview/widget/RecyclerView.Adapter.StateRestorationPolicy#PREVENT) upon initialization and waits for the first page to load before allowing state restoration.

but there are also open issues like https://issuetracker.google.com/issues/214253526, so this may be a library issue.

I'm going to leave this open to track the issue at the moment, and get 1.1 out the door, which does fix a number of other important issues. There's quite a lot of refactoring work to be done as well, and that might make the underlying issue more obvious.

**Comment by tinsukE** [comment] 2023-09-19 18:22
Was also affected by this issue on version 1.1. Note how from the app info, it seems to be running (not a cold start), as the "Force stop" button is enabled:

https://github.com/pachli/pachli-android/assets/1063155/6f4b66f6-87e0-4e24-a208-bdd263ee3cba

The scenarios you described above seem to be (1) hot start and (2) completely cold start. I think this is a case of (1.5) not so hot or cold start, when the app hasn't been closed, but has been suspended from memory, which caused its instance state to be saved and, when the user returns to the app, restored.

One could test this by:

A. On Developer options, enable "Don't keep activities". If you leave the app and return to it, the components' states will get saved and restored. On this case, the process is kept running and things like singletons would still be the same, kept in memory.
B. On Developer options, set the "Background process limit" to "No background processes". If you leave the app and return to it, the whole process will get suspended, but the components' states will still have gotten saved and restored. On this case, all will be instantiated again, but with a state to restore.
C. Send the app to the background, run `adb shell am kill app.pachli`, then return to the app.

Method C above should, as far as I understand, behave just as B. But I actually have been able to consistently reproduce the issue by using C (while not with A or B):


https://github.com/pachli/pachli-android/assets/1063155/e1542dc6-d1a4-461e-8a63-27775f9044b6

**Comment by foss-** [comment] 2023-09-20 08:21
Seeing timeline jumps in 1.1 when the timeline refreshes. Went through the settings a few times without finding the `Remember reading position` option. Should it be there? If so, where? If not, is remembering reading position the default in Pachli?

**Comment by caoilte** [comment] 2023-09-20 09:05
I think it's just broken. I've switched back to tusky for the moment. Hoping the fix doesn't require a rearchitecture

**Comment by nikclayton** [comment] 2023-09-20 09:08
@tinsukE -- thanks, that's very helpful. I'm also wondering whether the (inherited) `android:configChanges` settings in the manifest is causing problems, and is blocking the list / layout manager from restoring the state correctly. Lots to experiment with over the next few days.

@foss- -- there's no setting, it's supposed to just work. That it isn't is a bug that I'm focused on for the 1.2 release.

@caoilte -- that's reasonable. The tradeoff is that Tusky will have gaps in the timeline. I'll ping you here when the bug is fixed in Pachli.

**Comment by nikclayton** [comment] 2023-09-22 15:12
@tinsukE In your second video (signal-2023-09-19-202038.mp4) the different steps appear to be:

1. Open on home timeline
2. Swipe refresh to confirm you're at the top of the timeline
3. Scroll down a few screens
4. Open launcher
5. **DO SOMETHING HERE**
6. Open recents, select Pachli
7. Pachli re-opens, and briefly displays splash screen
8. Reading position is lost, user is at the most recent post

What are you doing at step 5?

I've tried to recreate that, and I can't.

At step 5 I'm running `adb shell am kill app.pachli`. This works -- I can see the "PROCESS ENDED" message in the logs when it completes, and at step 7 I also see splashscreen (which does not happen if I do the same process and skip step 5).

But when I do this the app correctly restores the previous reading position. I see that on both an emulator and a real Pixel 4a.

**Comment by tinsukE** [comment] 2023-09-22 17:32
@nikclayton indeed, step 5 is running `adb shell am kill app.pachli`.

And it is still easily reproducible for me:

https://github.com/pachli/pachli-android/assets/1063155/cfba030b-fe3f-4ad6-9225-ccfeb68d8584

Device info:
- OnePlus 6
- Android 13
- LineageOS 20-20230912

**Comment by nikclayton** [comment] 2023-09-22 19:15
@tinsukE Thanks.

Is there any chance you can trigger it in an emulator, and if you can, send the definition file you use for the emulator?

Because this is what I see if I do the same thing. In the following video I'm running the release version of Pachli 1.1 in an emulated Pixel 4a with the API 30 Android level. As you can see, when returning to the app from the "Recents" screen, after running the adb command (and observing the "PROCESS ENDED" message in the logs) the reading position isn't lost.

As you can imagine, not being able to reproduce this locally makes working out if I have a fix very difficult.

https://github.com/pachli/pachli-android/assets/773100/4233d976-0209-488f-bd9d-a65f42dc8ed7

**Comment by tinsukE** [comment] 2023-09-22 19:22
@nikclayton I completely understand. 

I think the earliest I can give this a try would be Sunday or Monday. But I'll check it out.

**Comment by nikclayton** [comment] 2023-09-22 19:28
Thanks, I appreciate that. For completeness I just tried in emulators running API 33 (which corresponds to Android 13) and API 34 (Android 14) and see the same thing as in my video -- the app resumes at the right reading position.

Just to confirm -- your videos were only running the adb kill command, yes? You hadn't made the "Don't keep activities" or "Background process limit" settings changes you mentioned in a prior post?

The only way I can reproduce the problem at the moment is to leave my physical device alone for a long enough period, typically overnight. I'm running a custom build on that at the moment with some small changes to see if they have any effect, but I won't know until tomorrow morning...

**Comment by tinsukE** [comment] 2023-09-22 19:34
Correct, no other change/setting than the adb command while the app is in background.

**Comment by tinsukE** [comment] 2023-09-25 07:04
Got some limited time this morning and I tried to reproduce the issue on a freshly created emulator, API 33, with the 1.1 APK downloaded from releases.

Couldn't so far, but this happened as soon as I issued the first `adb shell am kill app.pachli`: I can't get the TL to "remember" being at the top, it always resets to the middle of it, even after a pull to refresh. Maybe related?


https://github.com/pachli/pachli-android/assets/1063155/9b8c8245-9f1b-4673-9a42-7185d2ee80fd

I can try more later, but I could also run an APK with fix attempts/logging on my device where I can easily reproduce the original issue and see if it is fixed.

**Comment by nikclayton** [comment] 2023-09-25 10:42
Thanks @tinsukE. https://github.com/pachli/pachli-android/pull/94 is the current state of the work to fix this. I've discovered a lot of things that don't work, and with a testing cycle that takes 24 hours (because the only way I've found to reproduce the problem is to leave my phone overnight) it's a slow process.

My current working theory is as follows.

Before that PR, refreshing on a busy timeline could load up to 61 statuses:

1 status at your reading position
up to 30 statuses older than that (i.e., lower down in the timeline)
up to 30 statuses newer than that (i.e., higher up in the timeline)

This weirdness is because the Mastodon API operates on pages of content, and pages are "indexed" by the ID of the status immediately above or below that page. There's no Mastodon API call for "Give me the page of statuses that contains the status with ID X".

Suppose you're at the very top of the timeline and refresh. The adapter saves "position 0" as your reading position, and the data in the adapter is refreshed. It's been a while since you refreshed, and there are at least 30 new statuses. So the first page of data loaded in to the adapter contains, new statuses at positions 0 - 29, the status that was at position 0 when you refreshed is now at position 30, and the statuses that were at positions 1-30 are now at positions 31-60.

The adapter then restores your reading position to position 0. And now you're 30 statuses ahead of where you were.

I verified this by varying the page size from 30 to other numbers. I always ended up PAGE_SIZE statuses ahead of where my reading position was.

That PR *might* fix things. The three important changes I think are:

1. Not setting initialKey on the pager, let the adapter figure out where to restore from
2. Setting `jumpThreshold` large enough that the to-be-restored status can be found
3. Only manually restoring the reading position if savedInstanceState is null

Point 3 is still needed because if you don't, per https://developer.android.com/topic/libraries/architecture/saving-states, the reading position will be lost if the user dismisses the app from the "recents" screen, or installs a new version of the app.

**Comment by nikclayton** [comment] 2023-09-28 19:41
@tinsukE Moderately confident https://github.com/pachli/pachli-android/pull/133 is a good fix. It passed the "Restored the reading position after leaving the phone overnight" test, which is the only way I can reproduce the problem.

If it passes again tomorrow morning I'll merge (and get ready for a 1.2 release that includes the fix). Since you're the only person that can reproduce this at will on a physical device, if you get the chance to check that #133 fixes the problem for you too that would be very helpful.

**Comment by nikclayton** [comment] 2023-09-29 09:11
That passed the overnight test again, so I think this is good to go.

**Closed** 2023-09-29 09:10 UTC

**Comment by tinsukE** [comment] 2023-10-01 18:58
@nikclayton sorry for the delay, but yeah! The issue I could reproduce with `adb shell am kill` is gone with version 1.2.1.

Looking forward to seeing it work tomorrow morning after relaunching the app after a night of sleep (was affected by that too).

Any reason 1.2 and 1.2.1 aren't available on Play Store yet? Some staged rollout?

**Comment by nikclayton** [comment] 2023-10-02 20:54
Google has decided, for reasons that are wholly unclear, that 1.2 (and 1.2.1) don't meet their privacy policy requirements. Despite those requirements not changing since 1.0 was released. I'm trying to get this unblocked, but Google is a black box when it comes to this stuff.

**Comment by nikclayton** [comment] 2023-10-05 10:25
1.2.2 is out. As best as I can tell it didn't need to be a code change, but the objection was linking to the privacy policy on GitHub from the store page. Once I coped the policy to the Pachli website and updated the store page to link there it was approved.

**Comment by caoilte** [comment] 2023-10-05 12:40
I think you've nailed it! I finally feel close to parity with my old Twitter client.
