### ISSUE TITLE
Duplicate tabs should remember settings separately

### ISSUE THREAD

**Issue by ericlathrop** [pachli/pachli-android#579] opened 2024-03-31 00:50 UTC
**Describe the bug**

I added a second notifications tab. On the first I change the filters to show everything except boosts and favs, and on the second I set the filters to only show boosts and favs. It works until I close and re-open the app, then both tabs only show boosts and favs.

**To Reproduce**
1. Add a second notifications tab
2. Change the filters on the second notifications tab to be different from the first notifications tab
3. Close and re-open the app
4. Open the first notifications tab and notice the filter setting have changed to the same as the second notifications tab

**Expected behavior**
I expect both notifications tabs to maintain separate filter configurations

**Versions**
Pachli 2.3.0

Device:

Google Pixel 6a
Android version: 14
SDK level: 34

Mastodon Version: 4.2.8

**Affirmation**
[X] I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment] 2024-03-31 06:05
How did you add two Notification tabs?

The logic in the "Add a tab" button is supposed to prevent that because, as you've discovered, different settings for multiple tabs of the same type are not currently supported.

It's something I'm working on, but it's not ready yet, and probably won't be ready for 2.5.0.

**Comment by ericlathrop** [comment] 2024-03-31 13:38
To add a second tab I just:
1. Side menu
2. Account preferences
3. Tabs
4. "+" button
5. notifications

Weirdly I can add a 3rd notifications tab, but then it disappears from the "+" button and I can't add a 4th.

**Comment by nikclayton** [comment] 2024-04-01 20:10
Can you reproduce this in 2.4.0 or a clean install of Pachli Current?

What happens if you completely remove all the Notification tabs you've added, and then try and add them back one by one? Does it prevent you from adding a second and subsequent Notification tab?

**Comment by ericlathrop** [comment] 2024-04-01 22:48
The behavior persists in 2.4.0.

If I remove the second notifications tab, 2.4.0 prevents me from recreating it.

**Comment by nikclayton** [comment] 2024-04-28 22:30
Ok. Since multiple tabs of the same type is not supported, and appears to now be blocked as expected I'll close this out.

I have got plans for supporting multiple timelines of the same type (eg two notification tabs with different filters, or two home tabs, one of which hides posts that are replies) but that's probably a few months away - during the work I keep discovering other stuff that needs to be refactored first...

**Closed** 2024-04-28 22:30 UTC

**Comment by ericlathrop** [comment] 2024-04-28 23:55
Okay, thanks for considering this. I wish I could help, but I'm not a mobile dev.
