### ISSUE TITLE
Cannot upload photos for posting.

### ISSUE THREAD

**Issue by punkscience** [pachli/pachli-android#704] opened 2024-05-19 19:40 UTC
**Describe the bug**
On a Google Pixel 7, I cannot attach photos to a post. The upload gets all the way to the end and then says it failed. Had no issue with other clients I've been using recently.

**To Reproduce**
Take a picture. Go to "Attach Media" and attempt to upload the picture to a post. Upload fails.

**Expected behavior**
Picture should show up in the post.

**Versions**
Pachli 2.5.1

Device:

Google Pixel 7
Android version: 14
SDK level: 34

Account:

@punkscience_ns@me.dm
Version: 4.2.8

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

![Screenshot_20240519-165752](https://github.com/pachli/pachli-android/assets/204191/ab862c23-ac19-4d59-9caf-0b5b1a8646db)
![Screenshot_20240519-165823](https://github.com/pachli/pachli-android/assets/204191/c5311696-a44a-440f-bfeb-28c7ab2bc8b6)

**Comment by nikclayton** [comment] 2024-05-19 20:35
Sorry about that. Can you attach the picture you're trying to upload to this issue, and I'll try and reproduce (next week, I'm traveling at the moment)?

**Comment by punkscience** [comment] 2024-05-20 02:16
Sure. This is the one I was posting (a default recent photo from my Pixel 7). 
![PXL_20240519_195028204 PORTRAIT](https://github.com/pachli/pachli-android/assets/204191/33294ffe-9ffa-4bb4-8271-4ed126bbc19f)

**Comment by nikclayton** [comment] 2024-05-30 17:14
Hi, thanks for waiting.

I don't have a specific fix for this yet, but I have fixed the issue that meant the error message didn't contain any useful information, so the next time this happens we'll be able to figure out what the cause is.

That'll be in the next Pachli release.

**Comment by punkscience** [comment] 2024-06-03 11:57
Here's the result after the latest update. 403 error. 

![Screenshot_20240603-085543](https://github.com/pachli/pachli-android/assets/204191/cfe83a81-0500-402f-85d1-2ee425ebd35e)

**Comment by nikclayton** [comment] 2024-06-06 10:37
That's an error from your server, with not a lot of detail to figure out why.

Three things to try.

1. Can you try with the latest Pachli Current (https://play.google.com/store/apps/details?id=app.pachli.current)? I've changed that message further so if your server returns any additional information (besides the simple 403 error) it should be displayed. That might provide insight in to what is going on.

2. (long shot) Contact your server admins (@medium@me.dm I think) and ask if they have logs that show further details about why their server is returning a 403.

3. If posting the image in Pachli Current fails again, please immediately open a browser on the same phone, login to your server in the browser, and try and create a post uploading the same image from your phone. If that fails it's definitely a me.dm problem. If that succeeds something odd is going on...

**Comment by nikclayton** [comment] 2024-06-06 10:40
Separately, I've contacted them to see if they can provide a test account I can use to try and reproduce the problem.

**Comment by punkscience** [comment] 2024-06-06 20:23
1. Attempted with the Current version but this time got "null" instead
of 403 just after the upload. (Circle competes, error toast appears).

2. Will do.

3. Immediatly logged into me.dm with Chrome, posted the same test photo
from their Web site and it uploaded and posted without incident.




On June 6, 2024, Wilson ***@***.***> wrote:
> Separately, I've contacted them to see if they can provide a test
> account I can use to try and reproduce the problem.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/pachli/pachli-android/issues/704#issuecomment-
2151959496>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AABR3HZDBFPSSOI5TNVRXT3ZGA4CHAVCNFSM6AAAAABH6TUMV2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNJRHE2TSNBZGY>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by nikclayton** [comment] 2024-06-20 18:00
Thanks. There's been more updates to the Pachli Current that might shed more light on the issue. Are you able to try that?

Unfortunately I haven't heard from me.dm about a test account.

**Comment by punkscience** [comment] 2024-06-24 15:03
Unfortunately I still got the exact same behavior as pictured above. "An
error occurred: (null)". I might try to build myself locally so I can
see what's going on. 

 

On June 20, 2024, Wilson ***@***.***> wrote:
> Thanks. There's been more updates to the Pachli Current that might
> shed more light on the issue. Are you able to try that?
>
> Unfortunately I haven't heard from me.dm about a test account.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/pachli/pachli-android/issues/704#issuecomment-
2181244357>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AABR3H4TD7JDWFUE3VPETKDZIMKE5AVCNFSM6AAAAABH6TUMV2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOBRGI2DIMZVG4>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by nikclayton** [comment] 2024-06-25 11:05
Can you create a test account on another server with open registration (e.g., mastodon.social) and try and post the image there? I'd like to at least make sure this is a server-specific error. Thanks.

**Comment by punkscience** [comment] 2024-06-25 17:20
I can confirm that with a fresh account on mastodon.social, I did not
see the problem. So what we know so far is:

Official Mastodon Client + me.dm -> Succeeds
Web client (Phanpy) + me.dm -> Succeeds
Pachli + me.dm -> Fails
Pachli + mastodon.social -> Succeeds

On June 25, 2024, Wilson ***@***.***> wrote:
> Can you create a test account on another server with open registration
> (e.g., mastodon.social) and try and post the image there? I'd like to
> at least make sure this is a server-specific error. Thanks.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/pachli/pachli-android/issues/704#issuecomment-
2188641950>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AABR3H2EZ4CIRTNEKKCDPJTZJFFKNAVCNFSM6AAAAABH6TUMV2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOBYGY2DCOJVGA>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by nikclayton** [comment] 2024-07-01 13:21
me.dm folks are going to get back to me with a test account, that's good.

In the meantime mastodon.social is having issues posting images, and I've managed to capture one of the error responses. It looks like this:

```html
<!DOCTYPE html>
<html lang='en'>
<head>
<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
<meta charset='utf-8'>
<title>This page is not correct
 - Mastodon</title>
<meta content='width=device-width,initial-scale=1' name='viewport'>
<link rel="stylesheet" crossorigin="anonymous" href="/packs/css/common-34aedb4e.css" media="all" integrity="sha256-4NkOfBszT57lrnt7hVcTl1jQ+1gLZqpyVrYt3UWtfQA=" />
<link rel="stylesheet" crossorigin="anonymous" href="/packs/css/mastodon-light-006c2ed8.chunk.css" media="not all and (prefers-color-scheme: dark)" integrity="sha256-xBsdWGw6vAI2jmjyoaxlRKwBr2rvu5W9iNlWpHM9ZT4=" /><link rel="stylesheet" crossorigin="anonymous" href="/packs/css/default-df29489f.chunk.css" media="(prefers-color-scheme: dark)" integrity="sha256-doF8Txd82MumzHJheO31rrsjqIVM0ZrSzcP1LoJ96Cc=" />
<script src="/packs/js/common-d3b9b0d0d1a784d455f6.js" crossorigin="anonymous" integrity="sha256-ocneZWpYVTRxTOpJJ58uyoAK7R/0X2nlP4GLeBcZoqM="></script>
<script src="/packs/js/error-da74c4d70d8cc990c35d.chunk.js" crossorigin="anonymous" integrity="sha256-vuBo4Y6RTo2m0kQXzE97n7kCznI80Eykm1gjiBUuBT4="></script>
</head>
<body class='error'>
<div class='dialog'>
<div class='dialog__illustration'>
<img alt='Mastodon' src='/oops.png'>
</div>
<div class='dialog__message'>
<h1>We&#39;re sorry, but something went wrong on our end.
</h1>
</div>
</div>
</body>
</html>
```

I suspect me.dm has a similar problem in some cases -- instead of returning a JSON document that contains the error message I suspect it's returning arbitrary HTML.

I'll know more when I've experimented with the test account.

**Comment by nikclayton** [comment] 2024-07-03 16:30
Got the test account set up and I can immediately reproduce the problem.

[I'm going to report this to the me.dm folks and link them to this comment so they have the necessary details]

As I thought, it's caused by the me.dm server returning HTML instead of JSON when there's an error.

Specifically, it returns an HTTP 403 with a Cloudflare HTML error page in response to a POST to https://me.dm/api/v2/media.

I see the same error if I try and attach the image ([this one](https://private-user-images.githubusercontent.com/204191/331923461-33294ffe-9ffa-4bb4-8271-4ed126bbc19f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTkwNDQsIm5iZiI6MTcxOTk5ODc0NCwicGF0aCI6Ii8yMDQxOTEvMzMxOTIzNDYxLTMzMjk0ZmZlLTlmZmEtNGJiNC04MjcxLTRlZDEyNmJiYzE5Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwOTI1NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDVjODgxMDc2ZmNhOGQ0MWZhMWFkNWQwNTQzM2IwNjliMDM1NTY0MGIyNDNlMTliZmYzNDI1NzViOGNkMTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NeOcmKv7lw9oiLUzeV3V4OJBpteXvFdIGwzHGRHACis) from your comment at https://github.com/pachli/pachli-android/issues/704#issuecomment-2119547193)  to a post using the web interface at https://me.dm. In the web UI that also manifests as a generic "403" error popup at the bottom left of the screen with no additional information.

This is not supposed to happen; any errors are supposed to be returned as a JSON document containing an [Error](https://docs.joinmastodon.org/entities/Error/) so the client can show the user more information.

The complete response (headers and body) from the me.dm server is:

```text
date: Wed, 03 Jul 2024 16:12:18 GMT
content-type: text/html; charset=UTF-8
x-frame-options: SAMEORIGIN
referrer-policy: same-origin
cache-control: max-age=15
expires: Wed, 03 Jul 2024 16:12:33 GMT
set-cookie: __cf_bm=[REDACTED]; path=/; expires=Wed, 03-Jul-24 16:42:18 GMT; domain=.me.dm; HttpOnly; Secure; SameSite=None
vary: Accept-Encoding
strict-transport-security: max-age=15552000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 89d827ee98cabc6c-ZRH

<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" /><![endif]-->
<style>body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!-->
<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>
<!--<![endif]-->


</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> me.dm</h2>
      </div><!-- /.header -->

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">

              <span class="cf-no-screenshot error"></span>

          </div>
        </div>
      </div><!-- /.captcha-container -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">89d827ee98cabc6c</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">31.164.43.58</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script>
  window._cf_translation = {};


</script>

</body>
</html>
```

**Comment by nikclayton** [comment] 2024-07-03 17:48
On the plus side, I'm reworking the error handling further to provide a more detailed message for future troubleshooting. Here's what it looks like now.

<img width="45%" src="https://github.com/pachli/pachli-android/assets/773100/1b8e25e3-5cd6-4390-885c-b665a9720dc3">

**Comment by punkscience** [comment] 2024-07-04 01:54
That is much more helpful! So this has just become a me.dm problem. I'll
be curious if they do anything to address it. If not, I may move to
another instance so I can be free to use my client of choice! Thanks for
your investigation on this.

There is still a mystery here though and that is the error itself. So
even if it was returning the proper JSON response, why is it returning
an error at all?

On July 3, 2024, Wilson ***@***.***> wrote:
> On the plus side, I'm reworking the error handling further to provide
> a more detailed message for future troubleshooting. Here's what it
> looks like now.
>

image.png (view on web) <https://github.com/pachli/pachli-
android/assets/773100/1b8e25e3-5cd6-4390-885c-b665a9720dc3>

**Comment by nikclayton** [comment] 2024-07-04 12:50
> There is still a mystery here though and that is the error itself. So
> even if it was returning the proper JSON response, why is it returning
> an error at all?

The HTML in the error is from Cloudflare. So my best guess is they have configured Cloudflare to reverse proxy requests for me.dm to try and mitigate the risk of things like DDoS attacks, bots, and so on (e.g., https://www.cloudflare.com/ddos/ and https://www.cloudflare.com/application-services/products/bot-management/).

That's fine for real websites, but traffic from clients isn't necessarily going to look like that, and there's no mechanism for Cloudflare to e.g., insert an interstitial "I am not a bot" page, CAPTCHA, or anything like that when it's requests using the API.

Medium's support tell me this has been escalated to the relevant engineering team.

Since there's nothing Pachli can do about the underlying issue here I'll close this shortly with the PR that provides the improved error messages.

Thanks for your help in debugging this.

**Closed** 2024-07-04 17:16 UTC
