### ISSUE TITLE
search results for post URL show endless number of the same post

### ISSUE THREAD

**Issue by foss-** [pachli/pachli-android#338] opened 2023-12-30 23:02 UTC
If you think this should be filed with friendica instead of Pachli, please let me know. And if you have a hint were this problem may stem from I'll be glad to forward that information along.

**Describe the bug**
search results for post URL show endless number of the same post

**To Reproduce**
1. find post url via `… > Copy the link` - e.g. https://loma.ml/display/373ebf56-1165-8876-5363-14e295858477
2. open search via spotlight icon and paste url, and execute the search

Currently: search result shows post repeated endlessly and with infinite scroll

**Expected behavior**
search result should show post once

**Screenshots or video**
![1](https://github.com/pachli/pachli-android/assets/5708172/2160fadf-0678-442c-820a-fe4a4b32d435)

**Versions**
This is Friendica, version 2024.03-dev that is running at the web location https://pirati.ca. The database version is 1543/1543, the post update version is 1507/1543.
Pachli Current 2.1.1+51c2ef06

**Comment by nikclayton** [comment] 2023-12-31 16:04
FWIW I can't reproduve this from my account on mastodon.social (searching for https://loma.ml/display/373ebf56-1165-8876-5363-14e295858477) so it might be a server issue. More investigation will have to wait until I'm back in a couple of weeks.

**Comment by nikclayton** [comment] 2023-12-31 16:10
Also, I can't create an account on pirati.ca, can you paste the JSON response to fetching

https://pirati.ca/api/v2/search?q=https://loma.ml/display/373ebf56-1165-8876-5363-14e295858477&type=statuses

in to this issue?

**Comment by foss-** [comment] 2024-01-02 12:00
A test account with your email was created a while ago on pirati.ca so that is ready for login with the username you asked to be used.

<details>
<summary><b>Requested output:</b></summary>

```
{
    "accounts": [],
    "statuses": [
        {
            "id": "47344304",
            "created_at": "2023-12-24T18:20:03.000Z",
            "edited_at": null,
            "in_reply_to_id": null,
            "in_reply_to_status": null,
            "in_reply_to_account_id": null,
            "sensitive": false,
            "spoiler_text": "",
            "visibility": "public",
            "language": "de",
            "uri": "https://loma.ml/objects/373ebf56-1165-8876-5363-14e295858477",
            "url": "https://loma.ml/display/373ebf56-1165-8876-5363-14e295858477",
            "replies_count": 1,
            "reblogs_count": 3,
            "favourites_count": 7,
            "favourited": false,
            "reblogged": false,
            "muted": false,
            "bookmarked": false,
            "content": "<p>Weihnachtsgeschenke auch vom Friendica Projekt. Das Release 2023.12 wurde heute veröffentlicht. Vielen Dank an alle, die dieses unglaubliche Release auf die Beine gestellt haben! 👏👍🎄🎊🎉🎈</p><p><a class=\"mention hashtag status-link\" href=\"https://pirati.ca/search?tag=Fediverse\" rel=\"tag\">#<span>Fediverse</span></a> <a class=\"mention hashtag status-link\" href=\"https://pirati.ca/search?tag=Friendica\" rel=\"tag\">#<span>Friendica</span></a> <a class=\"mention hashtag status-link\" href=\"https://pirati.ca/search?tag=Weihnachten\" rel=\"tag\">#<span>Weihnachten</span></a> <a class=\"mention hashtag status-link\" href=\"https://pirati.ca/search?tag=Geschenk\" rel=\"tag\">#<span>Geschenk</span></a></p>",
            "reblog": null,
            "quote": null,
            "application": {
                "name": "[ˈloma] | Friendica"
            },
            "account": {
                "id": "4161292",
                "username": "feb",
                "acct": "feb@loma.ml",
                "display_name": "Matthias ✔",
                "locked": true,
                "bot": false,
                "discoverable": true,
                "group": false,
                "created_at": "2023-02-15T18:32:52.000Z",
                "note": "<p>Auf <a href=\"https://friendi.ca/\" target=\"_blank\" rel=\"noopener noreferrer\">FRIENDICA</a>  unterwegs, weil das besser geht.</p><p><img src=\"https://loma.ml/photo/6526289672640ef9bf05bd7610327992-0.png\" alt=\"Image/Photo\"></p><hr><p><strong>Der Sinn des Lebens</strong><br>Die Antwort ist '42'. Warum das so ist? Frag deine Eltern 😉<br><img src=\"https://loma.ml/photo/2145833958640efd83719d3202110193-0.jpg\" alt=\"\" title=\"\"></p><hr><p><img src=\"https://loma.ml/photo/3971293831640efc7a1dd4d734264703-0.gif\" style=\"width:270px;\" alt=\"3971293831640efc7a1dd4d734264703-0.gif\"></p><hr><p><a href=\"https://keyoxide.org/E57EF7A2E64D8A8A1845B3FFE47166BB9E3E18DF\" target=\"_blank\" rel=\"noopener noreferrer\">Keyoxide Nachweis</a></p><hr>",
                "url": "https://loma.ml/profile/feb",
                "avatar": "https://pirati.ca/photo/contact/320/373ebf56-1963-ed21-196d-912020415557?ts=1703950759",
                "avatar_static": "https://pirati.ca/photo/contact/320/373ebf56-1963-ed21-196d-912020415557?ts=1703950759&static=1",
                "header": "https://pirati.ca/photo/header/373ebf56-1963-ed21-196d-912020415557?ts=1703950759",
                "header_static": "https://pirati.ca/photo/header/373ebf56-1963-ed21-196d-912020415557?ts=1703950759&static=1",
                "followers_count": 423,
                "following_count": 711,
                "statuses_count": 3910,
                "last_status_at": "2024-01-01T00:00:00.000Z",
                "emojis": [],
                "fields": []
            },
            "media_attachments": [
                {
                    "id": "21363214",
                    "type": "image",
                    "url": "https://pirati.ca/photo/preview/21363214",
                    "preview_url": "https://pirati.ca/photo/preview/320/21363214",
                    "remote_url": "https://loma.ml/photo/13049897716587496273188714781887-0.png",
                    "text_url": "https://loma.ml/photo/13049897716587496273188714781887-0.png",
                    "description": "Friendica Release 2023.12 heute veröffentlicht.",
                    "blurhash": "|AOn]9gO0R]x0L0nFhtSaKznrqi{tl9$t6In$eEO01Rj0B5Xx]tOxr9e--t-x]5ARkxBxY-mwaxB0nninPNa}%EL-Nt8s;kQIpt7xVxuT1o}X9${0Uj[xVoz-mozR*IVIVNLI]?DnhNFIoW9t6OGIV-Q-mSgtQt6S#o|Si",
                    "meta": {
                        "original": {
                            "width": 512,
                            "height": 512,
                            "size": "512x512",
                            "aspect": 1
                        },
                        "small": {
                            "width": 512,
                            "height": 512,
                            "size": "512x512",
                            "aspect": 1
                        }
                    }
                }
            ],
            "mentions": [],
            "tags": [
                {
                    "name": "fediverse",
                    "url": "https://pirati.ca/search?tag=fediverse",
                    "history": [],
                    "following": false
                },
                {
                    "name": "friendica",
                    "url": "https://pirati.ca/search?tag=friendica",
                    "history": [],
                    "following": false
                },
                {
                    "name": "Weihnachten",
                    "url": "https://pirati.ca/search?tag=weihnachten",
                    "history": [],
                    "following": false
                },
                {
                    "name": "Geschenk",
                    "url": "https://pirati.ca/search?tag=geschenk",
                    "history": [],
                    "following": false
                }
            ],
            "emojis": [],
            "card": null,
            "poll": null,
            "friendica": {
                "title": "",
                "changed_at": "2023-12-30T22:45:17.000Z",
                "commented_at": "2023-12-24T18:24:22.000Z",
                "received_at": "2023-12-24T18:20:21.000Z",
                "delivery_data": {
                    "delivery_queue_count": null,
                    "delivery_queue_done": null,
                    "delivery_queue_failed": null
                },
                "dislikes_count": 0,
                "disliked": false,
                "visibility": {
                    "allow_cid": [],
                    "deny_cid": [],
                    "allow_gid": [],
                    "deny_gid": []
                }
            }
        }
    ],
    "hashtags": []
}
```
</details>

Enjoy your time off.

**Comment by nikclayton** [comment] 2024-01-30 14:20
Thanks for the info and the test account. I think this is a Friendica bug, which I'll be filing with them in a minute.

The problem is that the Mastodon API does not paginate search results like other API endpoints. Instead the client sends the query with an `offset` in to the result set. If it keeps getting results it repeats the search, increasing the offset by the number of results returned.

Suppose there are 40 results. Pachli requests the first 20 (`limit=20`), and gets back 20. Since `numberReturned == limit` it knows there might be more results, so it repeats the request with `offset = 20`, and gets back another 20 results.

So it does the search one more time, gets back 0 results, and knows that there are no more results.

That's what's supposed to happen. You can see this by trying these two URLs:

https://mastodon.social/api/v2/search?q=https%3A%2F%2Floma.ml%2Fdisplay%2F373ebf56-1165-8876-5363-14e295858477&type=statuses&resolve=true&limit=20&offset=0&following=false <-- requests 20 results, offset = 0, returns 1 result

https://mastodon.social/api/v2/search?q=https%3A%2F%2Floma.ml%2Fdisplay%2F373ebf56-1165-8876-5363-14e295858477&type=statuses&resolve=true&limit=20&offset=1&following=false <-- identical to the above except offset = 1, returns 0 results

Friendica's not doing that -- if you send the initial request (with offset = 0) you get back one result. If you send the same request but with offset = 1 you get back 1 result, not the 0 results that would be correct.

https://pirati.ca/api/v2/search?q=https%3A%2F%2Floma.ml%2Fdisplay%2F373ebf56-1165-8876-5363-14e295858477&type=statuses&resolve=true&limit=20&following=false&offset=0 <-- requests 20 results, offset = 0, returns 1 result

https://pirati.ca/api/v2/search?q=https%3A%2F%2Floma.ml%2Fdisplay%2F373ebf56-1165-8876-5363-14e295858477&type=statuses&resolve=true&limit=20&following=false&offset=1 <-- requests 20 results, offset = 1, returns 1 result, instead of the correct 0

So Pachli keeps getting a result with every request, so keeps checking to see if there are more results, and you get the infinite scrolling behaviour you observe.

I'll keep this open for the moment in case anyone from Friendica wants to comment here as well, but at the moment there's no much Pachli can do about this.

**Comment by nikclayton** [comment] 2024-02-18 16:51
Going to close this, as the Friendica folks have fixed this on their side; https://github.com/friendica/friendica/pull/13911

**Closed by nikclayton** 2024-02-18 16:51 UTC

**Comment by foss-** [comment] 2024-02-18 17:06
Verified in This is Friendica, version 2024.03-rc that is running at the web location https://pirati.ca. The database version is 1553/1553, the post update version is 1550/1550.

That shows a single post in the search results while This is Friendica, version 2024.03-dev that is running at the web location https://squeet.me. The database version is 1552/1552, the post update version is 1547/1550. still shows the infinite results.

Pachli 2.2.0
